name: Deploy to play.outplay.games

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Production
        uses: actions/checkout@master

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          envkey_GANACHE_MNEMONIC: ${{ secrets.GANACHE_MNEMONIC }}
          envkey_TESTNET_MNEMONIC: ${{ secrets.TESTNET_MNEMONIC }}
          envkey_INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          file_name: .env

      - name: Log in Heroku
        uses: sjdonado/heroku@master
        with:
          args: container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GANACHE_MNEMONIC: ${{ secrets.GANACHE_MNEMONIC }}
          TESTNET_MNEMONIC: ${{ secrets.TESTNET_MNEMONIC }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

      - name: Push to Heroku
        uses: sjdonado/heroku@master
        with:
          args: container:push -a game3-js web 
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GANACHE_MNEMONIC: ${{ secrets.GANACHE_MNEMONIC }}
          TESTNET_MNEMONIC: ${{ secrets.TESTNET_MNEMONIC }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

      - name: Release in Heroku
        uses: sjdonado/heroku@master
        with:
          args: container:release -a game3-js web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GANACHE_MNEMONIC: ${{ secrets.GANACHE_MNEMONIC }}
          TESTNET_MNEMONIC: ${{ secrets.TESTNET_MNEMONIC }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}